# Generated by Django 4.2.5 on 2024-11-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='response',
        ),
        migrations.AddField(
            model_name='lessonimage',
            name='response_position',
            field=models.IntegerField(null=True),
        ),
    ]
