# Generated by Django 4.2.5 on 2024-11-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lesson_response_lessonimage_response_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonimage',
            name='response_position',
        ),
        migrations.AddField(
            model_name='lesson',
            name='response',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
